"""Add mobileNumber column to Person table

Revision ID: 6de7e725b1bc
Revises: 45f481be943e
Create Date: 2024-12-23 22:26:40.036524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de7e725b1bc'
down_revision: Union[str, None] = '45f481be943e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('mobileNumber', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'mobileNumber')
    # ### end Alembic commands ###
